/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  BedtimeReminder as PrismaBedtimeReminder,
} from "@prisma/client";

export class BedtimeReminderServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.BedtimeReminderCountArgs, "select">
  ): Promise<number> {
    return this.prisma.bedtimeReminder.count(args);
  }

  async bedtimeReminders(
    args: Prisma.BedtimeReminderFindManyArgs
  ): Promise<PrismaBedtimeReminder[]> {
    return this.prisma.bedtimeReminder.findMany(args);
  }
  async bedtimeReminder(
    args: Prisma.BedtimeReminderFindUniqueArgs
  ): Promise<PrismaBedtimeReminder | null> {
    return this.prisma.bedtimeReminder.findUnique(args);
  }
  async createBedtimeReminder(
    args: Prisma.BedtimeReminderCreateArgs
  ): Promise<PrismaBedtimeReminder> {
    return this.prisma.bedtimeReminder.create(args);
  }
  async updateBedtimeReminder(
    args: Prisma.BedtimeReminderUpdateArgs
  ): Promise<PrismaBedtimeReminder> {
    return this.prisma.bedtimeReminder.update(args);
  }
  async deleteBedtimeReminder(
    args: Prisma.BedtimeReminderDeleteArgs
  ): Promise<PrismaBedtimeReminder> {
    return this.prisma.bedtimeReminder.delete(args);
  }
}
